version: '3'
services:
  proxy:
    build: ./nginx
    image: taskapp/proxy
    container_name: taskapp-compose.proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./next
    image: taskapp/app
    container_name: taskapp-compose.app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
  api:
    build: ./go/github.com/ke6ch/api
    image: taskapp/api
    container_name: taskapp-compose.api
    restart: always
    tty: true
    depends_on:
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "1323:1323"
    volumes:
      - ./go/github.com/ke6ch/api:/go/src/app
  mysql:
    build: ./mysql
    image: taskapp/mysql
    container_name: taskapp-compose.mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taskapp-compose.phpmyadmin
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY}
      PMA_HOSTS: ${PMA_HOSTS}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:80"
volumes:
  mysql:
