apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: taskapp/app
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 3000
      restartPolicy: Always
