apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml

configMapGenerator:
- name: app-config
  literals:
    - NODE_ENV=production
    - BASE_URL=http://api:1323
