apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: taskapp/api
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: api-secret
        ports:
        - containerPort: 1323
      restartPolicy: Always
