apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- volume.yaml
- service.yaml
- deployment.yaml

configMapGenerator:
- name: mysql-config
  files:
  - mysql.config

secretGenerator:
- name: mysql-secret
  files:
  - mysql-secret=root-password.txt
